### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by lependu**
As titled :)

### CODE REVIEW

**Comment by enobufs** [comment]
I once released v1.0.2 but someone was affected by a faulty change in it. I have reverted the change and published as v1.0.3 which is identical to v1.0.1.

I created [a branch](https://github.com/enobufs/lured/tree/feature/update_deps) which includes your changes, plus a fix for handing of error object in index.js.

I wonder if you could take a look at the change and see if that also works you?
If it works, I will publish it as v2.0.0 this time because Redis client has changed how the error objects are returned quite a bit.

**Comment by lependu** [comment]
Sorry, my mistake :flushed:  I think in  https://github.com/enobufs/lured/blob/7c195aea30a419545c3b3264e39d82ae54f9585a/index.js#L149
 i forgot to add `> -1`. 

Your solution is more appropiate. thank you sir! :+1: 
I would consider it a breaking change too.

**Comment by enobufs** [comment]
That was my insufficient review. Thanks for your comment.  I am going to modernize the code a bit (ES6 + promise) then will publish it as v2.

**Comment by lependu** [comment]
It souds great :+1:  Please, let me know, if you need any help.

**Pull request merged**
